#!/bin/bash
# https://github.com/AdguardTeam/AdGuardHome/wiki/Raspberry-Pi

wget https://static.adguard.com/adguardhome/release/AdGuardHome_linux_arm.tar.gz
tar xvf AdGuardHome_linux_arm.tar.gz
cd AdGuardHome
sudo ./AdGuardHome -s install

# http://ipaddres:3000
