#!/bin/sh
# https://community.ui.com/questions/Step-By-Step-Tutorial-Guide-Raspberry-Pi-with-UniFi-Controller-and-Pi-hole-from-scratch-headless/e8a24143-bfb8-4a61-973d-0b55320101dc

sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get autoremove && sudo apt-get autoclean
sudo apt-get install haveged -y
sudo apt install default-jdk -y

wget https://dl.ui.com/unifi/6.0.23/unifi_sysvinit_all.deb
sudo dpkg -i unifi_sysvinit_all.deb; sudo apt-get install -f -y
