#!/bin/sh

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git

cd
git clone git://github.com/StarshipEngineer/OpenVPN-Setup

cd OpenVPN-Setup
sudo chmod +x openvpnsetup.sh
sudo ./openvpnsetup.sh
